#!/usr/bin/env perl
use strict;
use lib qw(lib);

use File::Slurp qw( write_file );
use Email::Thread;
use Email::Folder;
use Mail::Thread::Arc;

my $threader = Email::Thread->new( Email::Folder->new('threadtest')->messages );
my $arc = Mail::Thread::Arc->new;
#$Mail::Thread::nosubject = 1;
$threader->thread;

my $i;
for my $thread ($threader->rootset) {
    ++$i;
    my $svg = $arc->render( $thread );
    write_file( "thread_$i.svg", $svg->xmlify );
}
