#!/usr/bin/env perl
use strict;
use lib qw(lib);

use File::Slurp qw( write_file );
use Email::Thread;
use Email::Folder;
use Mail::Thread::Arc;

my $threader = Email::Thread->new( Email::Folder->new('threadtest')->messages );
my $arc = Mail::Thread::Arc::Link->new;
#$Mail::Thread::nosubject = 1;
$threader->thread;

my $i;
for my $thread ( sort { $arc->date_of( $a ) <=> $arc->date_of( $b ) } $threader->rootset) {
    ++$i;
    my @messages;
    $thread->iterate_down(
        sub {
            my $c = shift;
            return unless $c->message;
            push @messages, $c;
        });

    my $svg = $arc->selected_message( undef )->render( $thread );
    write_file( "thread_$i.svg", $svg->xmlify );

    next;
    @messages = sort {
        $arc->date_of( $a ) <=> $arc->date_of( $b )
    } @messages;

    my $j;
    for my $message (@messages) {
        my $svg = $arc->selected_message( $message )->render( $thread );
        ++$j;
        write_file( "thread_$i\_$j.svg", $svg->xmlify );
    }
}

# follow with
# java -jar /usr/share/batik/lib/batik-rasterizer.jar -onload *.svg

package Mail::Thread::Arc::Link;

use base qw(Mail::Thread::Arc);

sub make_link {
    return "http://london.pm.org";
}
1;
